name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - "feature/*"
      - "fix/*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy-preview:
    name: Deploy Feature Branch to Firebase Preview
    needs: build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'  # Only deploy if NOT on the main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting Preview
        run: firebase hosting:channel:deploy pr-${{ github.event.number }} --token ${{ secrets.FIREBASE_TOKEN }}

  deploy-production:
    name: Deploy Main Branch to Firebase
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy if on main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Production
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
